kumuluzee:
  name: image-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://0.0.0.0:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImageMetadataDS
      connection-url: jdbc:postgresql://pg-image-metadata:5432/image-metadata
      username: dbuser
      password: postgres
  metrics:
    web-instrumentation:
      - name: images-endpoint
        url-pattern: /v1/images/*
    web-info:
      - name: info
        url-pattern: /v1/info/*
rest-properties:
  maintenance-mode: false
  broken: false
