sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"

env:
  global:
    - DOCKER_IMAGE=mista123/test:1.0.0$TRAVIS_JOB_NUMBER

script:
  - ./gradlew bootJar
  - docker build -t "$DOCKER_IMAGE" .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"