os: linux
sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"

env:
  global:
    - DOCKER_IMAGE=mista123/servicesdb:$TRAVIS_JOB_NUMBER
    - DOCKER_IMAGEL=mista123/servicesdb:latest

script:
  - docker build -t "$DOCKER_IMAGE" .
  - docker build -t "$DOCKER_IMAGEL" .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"
  - docker push "$DOCKER_IMAGEL"