version: '2'
services:
   
  services:
    container_name: serviceDB
    image: mista123/servicesdb
    networks:
      - net
    depends_on:
      - pg-image-metadata
    ports:
      - 8080:8080


  pg-image-metadata:
    container_name: pg-image-metadata
    image: postgres:13
    volumes:
      - image-db:/var/lib/postgresql/pg-image-metadata
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: dbuser
      POSTGRES_DB: image-metadata
    networks:
      - net
    ports:
      - 5433:5432

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:11.0.3
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - net
    ports:
      - 8081:8080
      

volumes:
  image-db:
    driver: local

networks:
  net:
    driver: bridge
